Update the scripts, remove Makefile

diff --git a/bin/dot b/bin/dot
--- a/bin/dot
+++ b/bin/dot
@@ -1,41 +1,39 @@
-#!/bin/bash
-#
-# dot
-#
-# `dot` handles installation, updates, things like that. Run it
-# periodically to make sure you're on the latest and greatest.
+#!/usr/bin/env bash
 
-set -e
-
-parent_dir="$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd -P)"
-dotfiles_dir="$(cd "$( dirname "$parent_dir" )" && pwd -P)"
-
-print_help() {
+print_help(){
   cat <<EOF
 dot -- dotfiles management
 
 Usage: dot [options]
 
+Default is to update the dotfiles and setup the system for work.
+
 Options:
-  -e, --edit    Open dotfiles directory for editing
-  -h, --help    Show this help message and exit
+ -e, --edit   Open dotfiles directory for editing
+ -l, --lint   Lint dotfiles
+ -h, --help   Show this help message and exti
 EOF
 }
 
 while test $# -gt 0; do
   case "$1" in
     "-h"|"--help") print_help;;
-    "-e"|"--edit") exec "$EDITOR" "$dotfiles_dir";;
-    *)
-      echo "Invalid option: $1"
-      print_help
-      ;;
+    "-e"|"--edit") exec e "${DOTFILES}";;
+    "-l"|"--lint") exec "${DOTFILES}/script/lint";;
+    *) echo "Invalid option: $1"; print_help; exit 1;;
   esac
-  exit
+  exit 0
   shift
 done
 
-# Install software
-export DOTFILES=$dotfiles_dir
-echo "› $dotfiles_dir/script/install"
-"$dotfiles_dir/script/install"
+# Update
+if [[ -n "$(git -C "${DOTFILES}" diff)" ]]
+then
+  echo "Commit the changes and try again."
+  exit 1
+fi
+
+git -C "${DOTFILES}" pull --rebase
+git -C "${DOTFILES}" submodule update --recursive
+git -C "${DOTFILES}" push
+"${DOTFILES}/script/bootstrap" --overwrite
diff --git a/script/lint b/script/lint
--- a/script/lint
+++ b/script/lint
@@ -2,22 +2,40 @@
 
 set -oe pipefail
 
+grepbang() {
+  rg -l --no-ignore "^#!$1" ||
+    grep -rl --exclude-dir=.git "^#\!$1" . || (
+      echo "failed to get files" && exit 1)
+}
+
 lintsh() {
-  echo -e "\nlinting $1 files:"
-  files=$(rg -l --no-ignore "^#!.*/$1" ||
-    grep -rl --exclude-dir=.git "^#\!.*/$1" . || (
-      echo "failed to get files" && exit 1))
-  echo "${files}"
-  echo "${files}" | xargs shellcheck
+  files=$({
+    grepbang ".*/sh"
+    grepbang ".*/bash"
+    grepbang "/usr/bin/env bash"
+    grepbang "/usr/bin/env sh"
+  })
+  print_run "shell" "$files"
+  run "$files" shellcheck
 }
 
 lintvim() {
-  echo -e "\nlinting vim files:"
   files=$(fd -e vim ||
     find . -name "*\.vim" || (
       echo "failed to get files" && exit 1))
-  echo "${files}"
-  echo "${files}" | xargs vint "$@"
+  print_run "vim" "$files"
+  run "$files" vint "$@"
+}
+
+print_run() {
+  echo -e "linting $1 files:"
+  echo -e "$2" | sort -u | sed "s|^| » |"
+  echo
+}
+
+run() {
+  files=$1; shift
+  echo "$files" | sort -u | xargs "$@"
 }
 
 case "${LINT:-all}" in
@@ -28,12 +46,10 @@ case "${LINT:-all}" in
       lintvim --error
       ;;
   "shellcheck")
-      lintsh sh
-      lintsh bash
+      lintsh
     ;;
   *)
-      lintsh sh
-      lintsh bash
+      lintsh
       lintvim --error
     ;;
 esac
