shfmt all

diff --git a/bin/dotr b/bin/dotr
--- a/bin/dotr
+++ b/bin/dotr
@@ -9,8 +9,8 @@ cd "${DOTFILES_ROOT}"
 # shellcheck source=/dev/null
 source "./script/logging.sh"
 
-print_help(){
-  cat <<EOF
+print_help() {
+    cat <<EOF
 dot -- dotfiles management
 
 Usage: dot [options]
@@ -27,25 +27,37 @@ EOF
 }
 
 while test $# -gt 0; do
-  case "$1" in
-    "-h"|"--help") print_help;;
-    "-e"|"--edit") exec e "${DOTFILES_ROOT}";;
-    "-l"|"--lint") exec "${DOTFILES_ROOT}/script/lint";;
-    "--no-push") NO_PUSH=true; shift; continue;;
-    "--no-gitconfig") [ -f "${DOTFILES_ROOT}/git/gitconfig.symlink" ] || touch "${DOTFILES_ROOT}/git/gitconfig.symlink"; shift; continue;;
-    *) echo "Invalid option: $1"; print_help; exit 1;;
-  esac
-  exit 0
+    case "$1" in
+    "-h" | "--help") print_help ;;
+    "-e" | "--edit") exec e "${DOTFILES_ROOT}" ;;
+    "-l" | "--lint") exec "${DOTFILES_ROOT}/script/lint" ;;
+    "--no-push")
+        NO_PUSH=true
+        shift
+        continue
+        ;;
+    "--no-gitconfig")
+        [ -f "${DOTFILES_ROOT}/git/gitconfig.symlink" ] || touch "${DOTFILES_ROOT}/git/gitconfig.symlink"
+        shift
+        continue
+        ;;
+    *)
+        echo "Invalid option: $1"
+        print_help
+        exit 1
+        ;;
+    esac
+    exit 0
 done
 
 # Update if successful
 [[ -z ${NO_PUSH:-} ]] && {
-  [[ -n "$(git -C "${DOTFILES_ROOT}" diff)" ]] && \
-    fail "Commit the changes and try again."
-  info "Rebasing on master"
-  git -C "${DOTFILES_ROOT}" pull --rebase
-  info "Updating submodules"
-  git -C "${DOTFILES_ROOT}" submodule update --recursive
+    [[ -n "$(git -C "${DOTFILES_ROOT}" diff)" ]] &&
+        fail "Commit the changes and try again."
+    info "Rebasing on master"
+    git -C "${DOTFILES_ROOT}" pull --rebase
+    info "Updating submodules"
+    git -C "${DOTFILES_ROOT}" submodule update --recursive
 }
 
 info "Bootstrapping..."
@@ -53,6 +65,6 @@ info "Bootstrapping..."
 
 # Update if successful
 [[ -z ${NO_PUSH:-} ]] && {
-  info "Pushing"
-  git -C "${DOTFILES_ROOT}" push
+    info "Pushing"
+    git -C "${DOTFILES_ROOT}" push
 }
diff --git a/script/lint b/script/lint
--- a/script/lint
+++ b/script/lint
@@ -8,47 +8,51 @@ cd "${DOTFILES_ROOT}"
 source "./script/logging.sh"
 
 grepbang() {
-  git -C "${DOTFILES_ROOT}" grep -El "^#!$1" || :
+    git -C "${DOTFILES_ROOT}" grep -El "^#!$1" || :
 }
 
 lintsh() {
-  files=$({
-    grepbang ".*/sh"
-    grepbang ".*/bash"
-    grepbang "/usr/bin/env bash"
-    grepbang "/usr/bin/env sh"
-  })
-  print_run "shell" "$files"
-  run "$files" shellcheck
+    files=$({
+        grepbang ".*/sh"
+        grepbang ".*/bash"
+        grepbang "/usr/bin/env bash"
+        grepbang "/usr/bin/env sh"
+    })
+    print_run "shell" "$files"
+    run "$files" shellcheck
 }
 
 lintvim() {
-  files=$(git -C "${DOTFILES_ROOT}" ls-files | grep -E "\.vim$" | grep -v "pack" ||
-    fail "failed to get vim files")
-  print_run "vim" "$files"
-  run "$files" vint "$@"
+    files=$(git -C "${DOTFILES_ROOT}" ls-files | grep -E "\.vim$" | grep -v "pack" ||
+        fail "failed to get vim files")
+    print_run "vim" "$files"
+    run "$files" vint "$@"
 }
 
 print_run() {
-  info "linting $1 files ...."
-  for i in $(echo -e "$2" | sort -u); do
-    debug "linting $i"
-  done
+    info "linting $1 files ...."
+    for i in $(echo -e "$2" | sort -u); do
+        debug "linting $i"
+    done
 }
 
 run() {
-  files=$1; shift
-  echo "$files" | sort -u | xargs "$@"
-  ok "$1"
+    files=$1
+    shift
+    echo "$files" | sort -u | xargs "$@"
+    ok "$1"
 }
 
 main() {
-  case "${LINT:-all}" in
-    "vint")         lintvim ;;
-    "vint-errors")  lintvim --error ;;
-    "shellcheck")   lintsh ;;
-    *)              lintsh; lintvim --error ;;
-  esac
+    case "${LINT:-all}" in
+    "vint") lintvim ;;
+    "vint-errors") lintvim --error ;;
+    "shellcheck") lintsh ;;
+    *)
+        lintsh
+        lintvim --error
+        ;;
+    esac
 }
 
 main || fail "lint failed"
