Rewrite the bootstrap scripts a little bit to make them more robust and faster

diff --git a/script/bootstrap b/script/bootstrap
--- a/script/bootstrap
+++ b/script/bootstrap
@@ -2,27 +2,57 @@
 #
 # bootstrap installs things.
 
+set -oe pipefail
+
 cd "$(dirname "$0")/.."
 DOTFILES_ROOT="$(pwd)"
+
+print_help() {
+  cat <<EOF
+bootstrap -- dotfiles management
+
+Usage: script/bootstrap [options]
+
+Options:
+  -o, --overwrite Replace the existing dotfiles with dotfile symlinks
+  -b, --backup    Backup the existing dotfiles before creating dotfile symlinks
+  -s, --skip      Skip the existing dotfiles
+  -h, --help      Show this help message and exit
+EOF
+}
+
+while test $# -gt 0; do
+  case "$1" in
+    "-h"|"--help") print_help; exit ;;
+    "-o"|"--overwrite" ) OVERWRITE_ALL=true;;
+    "-b"|"--backup") BACKUP_ALL=true;;
+    *)
+      echo "Invalid option: $1"
+      print_help
+      exit
+      ;;
+  esac
+  shift
+done
 
 set -e
 
 echo ''
 
 info () {
-  printf "  [ \033[00;34m..\033[0m ] $1"
+  printf "  [ \033[00;34m..\033[0m ] %s\n" "$1"
 }
 
 user () {
-  printf "\r  [ \033[0;33m?\033[0m ] $1 "
+  printf "\r  [ \033[0;33m?\033[0m ] %s " "$1"
 }
 
 success () {
-  printf "\r\033[2K  [ \033[00;32mOK\033[0m ] $1\n"
+  printf "\r\033[2K  [ \033[00;32mOK\033[0m ] %s\n" "$1"
 }
 
 fail () {
-  printf "\r\033[2K  [\033[0;31mFAIL\033[0m] $1\n"
+  printf "\r\033[2K  [\033[0;31mFAIL\033[0m] %s\n" "$1"
   echo ''
   exit
 }
@@ -55,116 +85,24 @@ setup_gitconfig () {
   fi
 }
 
-
-link_file () {
-  local src=$1 dst=$2
-
-  local overwrite= backup= skip=
-  local action=
-
-  if [ -f "$dst" -o -d "$dst" -o -L "$dst" ]
-  then
-
-    if [ "$overwrite_all" == "false" ] && [ "$backup_all" == "false" ] && [ "$skip_all" == "false" ]
-    then
-
-      local currentSrc="$(readlink $dst)"
-
-      if [ "$currentSrc" == "$src" ]
-      then
-
-        skip=true;
-
-      else
-
-        user "File already exists: $(basename "$src"), what do you want to do? [s]kip, [S]kip all, [o]verwrite, [O]verwrite all, [b]ackup, [B]ackup all?"
-        read -n 1 action
-
-        case "$action" in
-          o )
-            overwrite=true;;
-          O )
-            overwrite_all=true;;
-          b )
-            backup=true;;
-          B )
-            backup_all=true;;
-          s )
-            skip=true;;
-          S )
-            skip_all=true;;
-          * )
-            ;;
-        esac
-
-      fi
-
-    fi
-
-    overwrite=${overwrite:-$overwrite_all}
-    backup=${backup:-$backup_all}
-    skip=${skip:-$skip_all}
-
-    if [ "$overwrite" == "true" ]
-    then
-      rm -rf "$dst"
-      success "removed $dst"
-    fi
-
-    if [ "$backup" == "true" ]
-    then
-      mv "$dst" "${dst}.backup"
-      success "moved $dst to ${dst}.backup"
-    fi
-
-    if [ "$skip" == "true" ]
-    then
-      success "skipped $src"
-    fi
-  fi
-
-  if [ "$skip" != "true" ]  # "false" or empty
-  then
-    ln -s "$1" "$2"
-    success "linked $1 to $2"
-  fi
-}
-
 install_dotfiles () {
   info 'installing dotfiles'
-
-  local overwrite_all=false backup_all=false skip_all=false
-
-  for src in $(find "$DOTFILES_ROOT/" -maxdepth 2 -name '*.symlink')
-  do
-    # Check if we have a destination config file, which tells us where the
-    # symlink will endup:
-    postfix="$HOME/."
-    topic_folder=$(dirname "$src")
-    if [ -f "${topic_folder}/destination" ]; then
-      postfix="$HOME/$(cat "${topic_folder}/destination")"
-      mkdir -p "$postfix"
-    fi
-
-    dst="$postfix$(basename "${src%.*}")"
-    link_file "$src" "$dst"
-  done
+  cmd=(script/link_dotfile)
+  [[ ${OVERWRITE_ALL} == "true" ]] && cmd=("${cmd[@]}" --overwrite)
+  [[ ${BACKUP_ALL} == "true" ]] && cmd=("${cmd[@]}" --backup)
+  find "$DOTFILES_ROOT/" -maxdepth 2 -name '*.symlink' -exec "${cmd[@]}" {} \;
 }
 
 setup_gitconfig
 install_dotfiles
 
-# If we're on a Mac, let's install and setup homebrew.
-if [ "$(uname -s)" == "Darwin" ]
+info "installing dependencies"
+if bin/dot 2>&1 | tee /tmp/dotfiles-dot
 then
-  info "installing dependencies"
-  if source bin/dot > /tmp/dotfiles-dot 2>&1
-  then
-    success "dependencies installed"
-  else
-    fail "error installing dependencies"
-  fi
+  success "dependencies installed"
+else
+  fail "error installing dependencies"
 fi
 
 echo ''
-echo '  All installed!'
+echo '  All setup!'
